function(add_source NAME)
    message("Adding files to ${NAME}.")
    file (RELATIVE_PATH _relPath "${CMAKE_SOURCE_DIR}/${NAME}" "${CMAKE_CURRENT_SOURCE_DIR}")
    foreach (_src ${ARGN})
        message("File: ${_src}")
        if (_relPath)
            list (APPEND SRCS "${_relPath}/${_src}")
        else()
            list (APPEND SRCS "${_src}")
        endif()
    endforeach()
    set_property(GLOBAL APPEND PROPERTY SOURCES_${NAME} ${SRCS})
endfunction(add_source)